### ISSUE TITLE
live demo is broken in firefox 50

### ISSUE THREAD

**Issue by fingolfin** [drvy/minimal-block#5]
https://blog.drvy.net/minimal-block/ renders incorrectly, as the CSS cannot be loaded, due to a violation of the mixed content policy, see https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

Note that it  has https://drvy.github.io URLs in it, which immediately redirect.

**Comment by drvy** [comment]
@fingolfin 

There was a problem with the redirects.
- Content-Security-Policy meta-tag has been added to force upgrade unsecure requests.
- Main site.url has been changed to avoid useless redirection.

Demo should be properly working now.

Thanks!
